### ISSUE TITLE
[Question] always fallback to LSP for files that doesn't have an explicit formatter set.

### ISSUE THREAD

**Issue by ahmedelgabri** [stevearc/conform.nvim#670]
I want to always fallback to LSP if a filetype is not specified inside `formatters_by_ft` 

For example, I expect with a config like this that when I save `.toml` file, that it will use the LSP formatting, but this is not the case. Even with `default_format_opts = { lsp_format = 'fallback' }`

```lua
{
	'stevearc/conform.nvim',
	event = { 'BufWritePre' },
	cmd = { 'ConformInfo' },
	opts = {
		log_level = vim.log.levels.DEBUG,
		formatters_by_ft = {
			['*'] = { 'trim_whitespace', 'trim_newlines' },
			json = {
				'deno_fmt',
				'prettier',
				'jq',
				stop_after_first = true,
			},
                        -- More fts here…
		},
		format_on_save = function(bufnr)
			-- Disable with a global or buffer-local variable
			if vim.g.disable_autoformat or vim.b[bufnr].disable_autoformat then
				return
			end

			-- Disable autoformat for files in a certain path
			local bufname = vim.api.nvim_buf_get_name(bufnr)
			if bufname:match '/node_modules/' then
				return
			end

			return { timeout_ms = 500, lsp_format = 'fallback' }
		end,
	},
	init = function()
		vim.o.formatexpr = "v:lua.require'conform'.formatexpr()"
	end,
},

```

**Comment by stevearc** [comment]
Yes, this is due to an interaction with the magic filetype value of `"*"`, which I regret adding. There are two magic values, `"_"` for "any filetype that doesn't have an explicit configuration" and `"*"` for "append these values to all filetype configurations, even if they have an explicit list configured". So what is happening is you're never falling back to LSP because you _always_ have the `trim_whitespace` and `trim_newlines` formatters available for non-matching filetypes.

I haven't tested it, but you could try adding `['_'] = { lsp_format = "last" }`. If that doesn't work, you could change your `"*"` to `"_"`, though that will also change the behavior as mentioned. Lastly, this is all just sugar on top of calling the API directly, so you can always just explicitly call `conform.format` with the exact values that you want to use (same goes for returning opts from `format_on_save`).

**Comment by ahmedelgabri** [comment]
Ok, makes sense. One more question, why I can't add `lsp_format = "last"` to `*` then? Shouldn't this solve the issue?

If the above is not allowed, can I return `{ timeout_ms = 500, 'trim_whitespace', 'trim_newlines', lsp_format = 'last' }` from `format_on_save` or this also won't work?

**Comment by stevearc** [comment]
I just pushed a change to allow `_` to specify format opts

**Comment by ahmedelgabri** [comment]
Ok, so this works as in the LSP format runs, but not the trim whitespace or newlines. For example I don't have a formatted for `toml` set up, but I have an LSP. The formatted runs, but trimming doesn't work. even if I do `['_'] = { 'trim_whitespace', 'trim_newlines', lsp_fallback = "last" }`

```lua
{
	'stevearc/conform.nvim',
	event = { 'BufWritePre' },
	cmd = { 'ConformInfo' },
	opts = {
		log_level = vim.log.levels.DEBUG,
		formatters_by_ft = {
			['*'] = { 'trim_whitespace', 'trim_newlines' },
                        ['_'] = { lsp_fallback = "last" },
			json = {
				'deno_fmt',
				'prettier',
				'jq',
				stop_after_first = true,
			},
                        -- More fts here…
		},
		format_on_save = function(bufnr)
			-- Disable with a global or buffer-local variable
			if vim.g.disable_autoformat or vim.b[bufnr].disable_autoformat then
				return
			end

			return { timeout_ms = 500, lsp_format = 'fallback' }
		end,
	},
	init = function()
		vim.o.formatexpr = "v:lua.require'conform'.formatexpr()"
	end,
},
```

**Comment by stevearc** [comment]
Take the `lsp_format = 'fallback'` out of your `format_on_save` and put it into `default_format_opts`

**Comment by ahmedelgabri** [comment]
trimming still doesn't run. The only way both run (LSP formatting and trimming) is when I have an explicit config. But I want to avoid this when possible (If I know that the LSP can handle this, but I still ant whitespace trimming to run)

**Comment by stevearc** [comment]
This was because of a bit of hacky logic that was put in place to solve a problem that doesn't exist anymore. Now that we can specify formatter options (especially `lsp_format`) in the filetype formatters table, we can get rid of it and make things a bit more intuitive. If you update conform the logic should work as expected now!
